# Generated by Django 4.0.6 on 2022-07-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_autismcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalcategory',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='generalcategory',
            name='skil',
        ),
        migrations.RemoveField(
            model_name='specialskilledcategory',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='specialskilledcategory',
            name='skil',
        ),
        migrations.DeleteModel(
            name='AutismCategory',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='GeneralCategory',
        ),
        migrations.DeleteModel(
            name='Skil',
        ),
        migrations.DeleteModel(
            name='SpecialSkilledCategory',
        ),
    ]
