# Generated by Django 4.0.6 on 2022-07-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_autismcategory_user_generalcategory_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skil',
            new_name='Skils',
        ),
        migrations.RenameField(
            model_name='autismcategory',
            old_name='skil',
            new_name='skils',
        ),
        migrations.RenameField(
            model_name='generalcategory',
            old_name='skil',
            new_name='skils',
        ),
        migrations.RenameField(
            model_name='skils',
            old_name='skil',
            new_name='skils',
        ),
        migrations.RenameField(
            model_name='specialskilledcategory',
            old_name='skil',
            new_name='skils',
        ),
    ]
