# Generated by Django 4.0.6 on 2022-07-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_rename_skil_skils_rename_skil_autismcategory_skils_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autismcategory',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='generalcategory',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='specialskilledcategory',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
