# Generated by Django 4.0.6 on 2022-07-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_autismcategory_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalcategory',
            name='email',
        ),
    ]
