# Generated by Django 4.0.6 on 2022-07-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_remove_generalcategory_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalcategory',
            name='skils',
        ),
        migrations.RemoveField(
            model_name='generalcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specialskilledcategory',
            name='skils',
        ),
        migrations.RemoveField(
            model_name='specialskilledcategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='AutismCategory',
        ),
        migrations.DeleteModel(
            name='GeneralCategory',
        ),
        migrations.DeleteModel(
            name='JobApply',
        ),
        migrations.DeleteModel(
            name='SpecialSkilledCategory',
        ),
    ]
