# Generated by Django 4.0.6 on 2022-07-22 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0011_specialskilledcategory_jobapply_generalcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autismcategory',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None),
        ),
        migrations.AlterField(
            model_name='autismcategory',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalcategory',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None),
        ),
        migrations.AlterField(
            model_name='generalcategory',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialskilledcategory',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None),
        ),
        migrations.AlterField(
            model_name='specialskilledcategory',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
