# Generated by Django 4.0.6 on 2022-07-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetailsinformation',
            old_name='Country',
            new_name='country',
        ),
    ]
