# Generated by Django 4.0.6 on 2022-07-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_city_country_street_state_city_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetailsinformation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='companydetailsinformation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='companydetailsinformation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='companydetailsinformation',
            name='street',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RemoveField(
            model_name='street',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CompanyDetailsInformation',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
