# Generated by Django 4.0.6 on 2022-07-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetailsInformation',
        ),
    ]
