# Generated by Django 4.0.6 on 2022-07-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetailsInformation',
        ),
    ]
