# Generated by Django 4.0.6 on 2022-07-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_remove_companydetailsinformation_industry_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetailsinformation',
            name='industry_type',
        ),
        migrations.DeleteModel(
            name='IndustryType',
        ),
    ]
