# Generated by Django 4.0.6 on 2022-07-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_industrytype_companydetailsinformation_industry_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetailsInformation',
        ),
        migrations.DeleteModel(
            name='IndustryType',
        ),
    ]
