# Generated by Django 4.0.6 on 2022-07-16 12:51

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0015_delete_companydetailsinformation_delete_industrytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetailsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('are_you_new_entrepreneur', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=20)),
                ('year_of_establishment', models.CharField(max_length=4)),
                ('company_size', models.CharField(choices=[('1-15', '1-15 Employees'), ('16-30', '16-30 Employees'), ('31-50', '31-50 Employees')], max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('address', models.TextField(max_length=30)),
                ('industry_type', models.ManyToManyField(to='company.industrytype')),
                ('industy_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.industrycategory')),
            ],
        ),
    ]
