# Generated by Django 4.0.6 on 2022-07-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetailsInformation',
        ),
        migrations.DeleteModel(
            name='IndustryCategory',
        ),
        migrations.DeleteModel(
            name='IndustryType',
        ),
    ]
