# Generated by Django 4.0.6 on 2022-07-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_requirements', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educaton', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.IntegerField()),
                ('job_context', models.TextField(max_length=400)),
                ('job_responsibilities', models.TextField(max_length=10000)),
                ('location', models.CharField(max_length=20)),
                ('benefits', models.TextField(max_length=300)),
                ('additional_requirements', models.ManyToManyField(to='company.additionalrequirement')),
                ('educational_requirement', models.ManyToManyField(to='company.educationalrequirement')),
                ('employment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.employmentstatu')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.salary')),
                ('work_experience', models.ManyToManyField(to='company.experience')),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.workplace')),
            ],
        ),
    ]
