# Generated by Django 4.0.6 on 2022-07-18 16:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_companydetailsinformation_user_jobrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetailsinformation',
            name='contact_person_email',
        ),
        migrations.RemoveField(
            model_name='companydetailsinformation',
            name='contact_person_name',
        ),
        migrations.AlterField(
            model_name='companydetailsinformation',
            name='are_you_new_entrepreneur',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='companydetailsinformation',
            name='contact_person_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None),
        ),
    ]
