# Generated by Django 4.0.6 on 2022-07-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_remove_companydetailsinformation_contact_person_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetailsInformation',
        ),
    ]
