# Generated by Django 4.0.6 on 2022-07-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_companydetailsinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetailsInformation',
        ),
    ]
