# Generated by Django 4.0.6 on 2022-07-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_companydetailsinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetailsInformation',
        ),
    ]
